name: 🚀 Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 📦 Install dependencies
      run: npm install

    - name: ✅ Run tests (optional)
      run: echo "No tests yet, but you can add them to this step."

    - name: 🧪 Check Swagger validity (optional)
      run: |
        if [ -f "swagger.yaml" ]; then
          npx @apidevtools/swagger-cli validate swagger.yaml
        else
          echo "No swagger.yaml found"
        fi

    - name: ✅ Lint (optional)
      run: echo "Add eslint if needed"
